import type { LucideIcon } from 'lucide-react';
import { Angry, Coffee, Frown, Heart, PawPrint, Smile, Sparkles } from 'lucide-react';

export interface Emoji {
  emoji: string;
  description: string;
}

export interface EmojiCategory {
  name: string;
  icon: LucideIcon;
  emojis: Emoji[];
}

export const emojiCategories: Record<string, EmojiCategory> = {
  joy: {
    name: "Joy",
    icon: Smile,
    emojis: [
      { emoji: "😀", description: "grinning face" },
      { emoji: "😃", description: "grinning face with big eyes" },
      { emoji: "😄", description: "grinning face with smiling eyes" },
      { emoji: "😁", description: "beaming face with smiling eyes" },
      { emoji: "😆", description: "grinning squinting face" },
      { emoji: "😅", description: "grinning face with sweat" },
      { emoji: "😂", description: "face with tears of joy" },
      { emoji: "🤣", description: "rolling on the floor laughing" },
      { emoji: "😊", description: "smiling face with smiling eyes" },
      { emoji: "😇", description: "smiling face with halo" },
      { emoji: "🙂", description: "slightly smiling face" },
      { emoji: "🙃", description: "upside-down face" },
      { emoji: "😉", description: "winking face" },
      { emoji: "😌", description: "relieved face" },
      { emoji: "😍", description: "smiling face with heart-eyes" },
      { emoji: "🥰", description: "smiling face with hearts" },
      { emoji: "😘", description: "face blowing a kiss" },
      { emoji: "😗", description: "kissing face" },
      { emoji: "😙", description: "kissing face with smiling eyes" },
      { emoji: "😚", description: "kissing face with closed eyes" },
      { emoji: "😋", description: "face savoring food" },
      { emoji: "😛", description: "face with tongue" },
      { emoji: "😜", description: "winking face with tongue" },
      { emoji: "🤪", description: "zany face" },
      { emoji: "😝", description: "squinting face with tongue" },
      { emoji: "🤗", description: "hugging face" },
      { emoji: "🥳", description: "partying face" },
      { emoji: "🤩", description: "star-struck" },
      { emoji: "😎", description: "smiling face with sunglasses" },
      { emoji: "🤓", description: "nerd face" },
      { emoji: "🥲", description: "smiling face with tear" },
    ],
  },
  sadness: {
    name: "Sadness",
    icon: Frown,
    emojis: [
      { emoji: "😟", description: "worried face" },
      { emoji: "🙁", description: "slightly frowning face" },
      { emoji: "☹️", description: "frowning face" },
      { emoji: "😮", description: "face with open mouth" },
      { emoji: "😯", description: "hushed face" },
      { emoji: "😲", description: "astonished face" },
      { emoji: "😳", description: "flushed face" },
      { emoji: "🥺", description: "pleading face" },
      { emoji: "😦", description: "frowning face with open mouth" },
      { emoji: "😧", description: "anguished face" },
      { emoji: "😨", description: "fearful face" },
      { emoji: "😰", description: "anxious face with sweat" },
      { emoji: "😥", description: "sad but relieved face" },
      { emoji: "😢", description: "crying face" },
      { emoji: "😭", description: "loudly crying face" },
      { emoji: "😱", description: "face screaming in fear" },
      { emoji: "😖", description: "confounded face" },
      { emoji: "😣", description: "persevering face" },
      { emoji: "😞", description: "disappointed face" },
      { emoji: "😓", description: "downcast face with sweat" },
      { emoji: "😩", description: "weary face" },
      { emoji: "😫", description: "tired face" },
      { emoji: "🥱", description: "yawning face" },
    ],
  },
  anger: {
    name: "Anger",
    icon: Angry,
    emojis: [
      { emoji: "😠", description: "angry face" },
      { emoji: "😡", description: "pouting face" },
      { emoji: "🤬", description: "face with symbols on mouth" },
      { emoji: "😤", description: "face with steam from nose" },
      { emoji: "💢", description: "anger symbol" },
      { emoji: "👿", description: "angry face with horns" },
      { emoji: "👺", description: "goblin" },
      { emoji: "💀", description: "skull" },
      { emoji: "☠️", description: "skull and crossbones" },
      { emoji: "💣", description: "bomb" },
    ],
  },
  love: {
    name: "Love",
    icon: Heart,
    emojis: [
      { emoji: "❤️", description: "red heart" },
      { emoji: "🧡", description: "orange heart" },
      { emoji: "💛", description: "yellow heart" },
      { emoji: "💚", description: "green heart" },
      { emoji: "💙", description: "blue heart" },
      { emoji: "💜", description: "purple heart" },
      { emoji: "🖤", description: "black heart" },
      { emoji: "🤍", description: "white heart" },
      { emoji: "🤎", description: "brown heart" },
      { emoji: "💔", description: "broken heart" },
      { emoji: "❤️‍🔥", description: "heart on fire" },
      { emoji: "❤️‍🩹", description: "mending heart" },
      { emoji: "❣️", description: "heart exclamation" },
      { emoji: "💕", description: "two hearts" },
      { emoji: "💞", description: "revolving hearts" },
      { emoji: "💓", description: "beating heart" },
      { emoji: "💗", description: "growing heart" },
      { emoji: "💖", description: "sparkling heart" },
      { emoji: "💘", description: "heart with arrow" },
      { emoji: "💝", description: "heart with ribbon" },
      { emoji: "💟", description: "heart decoration" },
      { emoji: "🫶", description: "heart hands" },
    ],
  },
  excitement: {
    name: "Excitement",
    icon: Sparkles,
    emojis: [
      { emoji: "✨", description: "sparkles" },
      { emoji: "🌟", description: "glowing star" },
      { emoji: "💫", description: "dizzy" },
      { emoji: "🎉", description: "party popper" },
      { emoji: "🎊", description: "confetti ball" },
      { emoji: "🎈", description: "balloon" },
      { emoji: "💯", description: "hundred points" },
      { emoji: "🙌", description: "raising hands" },
      { emoji: "🔥", description: "fire" },
      { emoji: "🚀", description: "rocket" },
      { emoji: "🤯", description: "exploding head" },
      { emoji: "💥", description: "collision" },
      { emoji: "🤩", description: "star-struck" },
    ],
  },
  animals: {
    name: "Animals",
    icon: PawPrint,
    emojis: [
        { emoji: "🐶", description: "dog face" },
        { emoji: "🐱", description: "cat face" },
        { emoji: "🐭", description: "mouse face" },
        { emoji: "🐹", description: "hamster" },
        { emoji: "🐰", description: "rabbit face" },
        { emoji: "🦊", description: "fox" },
        { emoji: "🐻", description: "bear" },
        { emoji: "🐼", description: "panda" },
        { emoji: "🐨", description: "koala" },
        { emoji: "🐯", description: "tiger face" },
        { emoji: "🦁", description: "lion face" },
        { emoji: "🐮", description: "cow face" },
        { emoji: "🐷", description: "pig face" },
        { emoji: "🐸", description: "frog" },
        { emoji: "🐵", description: "monkey face" },
        { emoji: "🐔", description: "chicken" },
        { emoji: "🐧", description: "penguin" },
        { emoji: "🐦", description: "bird" },
        { emoji: "🐤", description: "baby chick" },
        { emoji: "🦆", description: "duck" },
        { emoji: "🦅", description: "eagle" },
        { emoji: "🦉", description: "owl" },
        { emoji: "🦇", description: "bat" },
        { emoji: "🐺", description: "wolf" },
        { emoji: "🐗", description: "boar" },
        { emoji: "🐴", description: "horse face" },
        { emoji: "🦄", description: "unicorn" },
        { emoji: "🐝", description: "honeybee" },
        { emoji: "🐛", description: "bug" },
        { emoji: "🦋", description: "butterfly" },
        { emoji: "🐌", description: "snail" },
        { emoji: "🐞", description: "lady beetle" },
        { emoji: "🐜", description: "ant" },
        { emoji: "🦗", description: "cricket" },
        { emoji: "🕷️", description: "spider" },
        { emoji: "🦂", description: "scorpion" },
        { emoji: "🐢", description: "turtle" },
        { emoji: "🐍", description: "snake" },
        { emoji: "🦎", description: "lizard" },
        { emoji: "🦖", description: "T-Rex" },
        { emoji: "🦕", description: "sauropod" },
        { emoji: "🐙", description: "octopus" },
        { emoji: "🦑", description: "squid" },
        { emoji: "🦐", description: "shrimp" },
        { emoji: "🦀", description: "crab" },
        { emoji: "🐡", description: "blowfish" },
        { emoji: "🐠", description: "tropical fish" },
        { emoji: "🐟", description: "fish" },
        { emoji: "🐬", description: "dolphin" },
        { emoji: "🐳", description: "spouting whale" },
        { emoji: "🐋", description: "whale" },
        { emoji: "🦈", description: "shark" },
        { emoji: "🐊", description: "crocodile" },
    ],
  },
  food: {
    name: "Food",
    icon: Coffee,
    emojis: [
        { emoji: "🍏", description: "green apple" },
        { emoji: "🍎", description: "red apple" },
        { emoji: "🍐", description: "pear" },
        { emoji: "🍊", description: "tangerine" },
        { emoji: "🍋", description: "lemon" },
        { emoji: "🍌", description: "banana" },
        { emoji: "🍉", description: "watermelon" },
        { emoji: "🍇", description: "grapes" },
        { emoji: "🍓", description: "strawberry" },
        { emoji: "🍈", description: "melon" },
        { emoji: "🍒", description: "cherries" },
        { emoji: "🍑", description: "peach" },
        { emoji: "🥭", description: "mango" },
        { emoji: "🍍", description: "pineapple" },
        { emoji: "🥥", description: "coconut" },
        { emoji: "🥝", description: "kiwi fruit" },
        { emoji: "🍅", description: "tomato" },
        { emoji: "🍆", description: "eggplant" },
        { emoji: "🥑", description: "avocado" },
        { emoji: "🥦", description: "broccoli" },
        { emoji: "🥬", description: "leafy green" },
        { emoji: "🥒", description: "cucumber" },
        { emoji: "🌶️", description: "hot pepper" },
        { emoji: "🌽", description: "corn" },
        { emoji: "🥕", description: "carrot" },
        { emoji: "🧄", description: "garlic" },
        { emoji: "🧅", description: "onion" },
        { emoji: "🥔", description: "potato" },
        { emoji: "🍠", description: "roasted sweet potato" },
        { emoji: "🥐", description: "croissant" },
        { emoji: "🥯", description: "bagel" },
        { emoji: "🍞", description: "bread" },
        { emoji: "🥖", description: "baguette bread" },
        { emoji: "🥨", description: "pretzel" },
        { emoji: "🧀", description: "cheese wedge" },
        { emoji: "🥚", description: "egg" },
        { emoji: "🍳", description: "cooking" },
        { emoji: "🥞", description: "pancakes" },
        { emoji: "🥓", description: "bacon" },
        { emoji: "🥩", description: "cut of meat" },
        { emoji: "🍗", description: "poultry leg" },
        { emoji: "🍖", description: "meat on bone" },
        { emoji: "🌭", description: "hot dog" },
        { emoji: "🍔", description: "hamburger" },
        { emoji: "🍟", description: "french fries" },
        { emoji: "🍕", description: "pizza" },
        { emoji: "🥪", description: "sandwich" },
        { emoji: "🥙", description: "stuffed flatbread" },
        { emoji: "🌮", description: "taco" },
        { emoji: "🌯", description: "burrito" },
        { emoji: "🥗", description: "green salad" },
        { emoji: "🥘", description: "shallow pan of food" },
        { emoji: "🥫", description: "canned food" },
        { emoji: "🍝", description: "spaghetti" },
        { emoji: "🍜", description: "steaming bowl" },
        { emoji: "🍲", description: "pot of food" },
        { emoji: "🍛", description: "curry rice" },
        { emoji: "🍣", description: "sushi" },
        { emoji: "🍱", description: "bento box" },
        { emoji: "🥟", description: "dumpling" },
        { emoji: "🍤", description: "fried shrimp" },
        { emoji: "🍙", description: "rice ball" },
        { emoji: "🍚", description: "cooked rice" },
        { emoji: "🍘", description: "rice cracker" },
        { emoji: "🍥", description: "fish cake with swirl" },
        { emoji: "🥠", description: "fortune cookie" },
        { emoji: "🥮", description: "moon cake" },
        { emoji: "🍢", description: "oden" },
        { emoji: "🍡", description: "dango" },
        { emoji: "🍧", description: "shaved ice" },
        { emoji: "🍨", description: "ice cream" },
        { emoji: "🍦", description: "soft ice cream" },
        { emoji: "🥧", description: "pie" },
        { emoji: "🧁", description: "cupcake" },
        { emoji: "🍰", description: "shortcake" },
        { emoji: "🎂", description: "birthday cake" },
        { emoji: "🍮", description: "custard" },
        { emoji: "🍭", description: "lollipop" },
        { emoji: "🍬", description: "candy" },
        { emoji: "🍫", description: "chocolate bar" },
        { emoji: "🍿", description: "popcorn" },
        { emoji: "🍩", description: "doughnut" },
        { emoji: "🍪", description: "cookie" },
        { emoji: "🌰", description: "chestnut" },
        { emoji: "🥜", description: "peanuts" },
        { emoji: "🍯", description: "honey pot" },
        { emoji: "🥛", description: "glass of milk" },
        { emoji: "🍼", description: "baby bottle" },
        { emoji: "☕", description: "hot beverage" },
        { emoji: "🍵", description: "teacup without handle" },
        { emoji: "🧃", description: "beverage box" },
        { emoji: "🥤", description: "cup with straw" },
        { emoji: "🍶", description: "sake" },
        { emoji: "🍺", description: "beer mug" },
        { emoji: "🍻", description: "clinking beer mugs" },
        { emoji: "🥂", description: "clinking glasses" },
        { emoji: "🍷", description: "wine glass" },
        { emoji: "🥃", description: "tumbler glass" },
        { emoji: "🍸", description: "cocktail glass" },
        { emoji: "🍹", description: "tropical drink" },
        { emoji: "🧉", description: "mate" },
        { emoji: "🍾", description: "bottle with popping cork" },
        { emoji: "🧊", description: "ice cube" },
        { emoji: "🥄", description: "spoon" },
        { emoji: "🍴", description: "fork and knife" },
        { emoji: "🍽️", description: "fork and knife with plate" },
        { emoji: "🥣", description: "bowl with spoon" },
        { emoji: "🥡", description: "takeout box" },
        { emoji: "🥢", description: "chopsticks" },
        { emoji: "🧂", description: "salt" },
    ],
  },
};

export const allEmojis: Emoji[] = Object.values(emojiCategories).flatMap(category => category.emojis);
